# Site settings
title: Adam Rafeek
email: adam_rafeek@hotmail.com
description: A description! Do we really want this? Who knows?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamrafeek.com" # the base hostname & protocol for your site
twitter_username: AdamRafeek
github_username:  arafeek

# Build settings
markdown: kramdown

# SASS settings
sass:
  style: compressed

# For setting the link structure to blog posts
permalink: /posts/:year/:month/:day/:title.html
